name: CI - Pipeline Informatif

on: push

jobs:
  Demonstration_CI:
    runs-on: ubuntu-latest
    env:
      STEP1 : " Le code vient d'être poussé sur le dépôt."
    steps:
      - name: Étape 1 - Initialisation
        run: echo "$STEP1"
      - name: Étape 2 - Récupération du code
        run: echo "STEP2= ${{vars.STEP2}}"

      - name: Étape 3 - Build
        run: echo "Build en cours..."

      - name: Étape 4 - Tests
        run: echo "Lancement des tests..."

      - name: Étape 5 - Packaging
        run: echo "Packaging de l'application..."

      - name: Étape 6 - Fin du pipeline
        run: echo "Pipeline terminé avec succès !"