name: Testing github workflows
on: push
jobs:
  init:
    runs-on: ubuntu:latest
    steps:
      - run: echo " Bonjour, je suis un workflow de test pour les github actions"
      - run: echo $HOSTNAME
